### ISSUE TITLE
Get the instances of a given model

### ISSUE THREAD

**Issue by thendrich** [KE-works/pykechain#113] opened 2017-05-29 11:38 UTC
Similar to the some_part.instance.model() method but the other way around (result as a PartSet I guess)

**Comment by jberends** [comment] 2017-05-31 08:04
```
bike_model.instances() == project.parts(model=bike_model) -> partSet
```

**Comment by jberends** [comment] 2017-05-31 08:07
This is in effect a duplicate of the `project.parts(model=bike_model)` call. The question is if we provide these kind of convenient methods.

**Comment by jberends** [comment] 2017-06-04 20:26
see #123

**Comment by jberends** [comment] 2017-06-05 10:06
will be released in 1.8

**Closed** 2017-06-05 10:06 UTC
Labels: agreed, enhancement
